[package]
name = "ptp-trace"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.26"
crossterm = "0.27"
tokio = { version = "1.0", features = ["full"] }
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
socket2 = "0.5"
phf = { version = "0.11", features = ["macros"] }
if-addrs = "0.13"
chrono = { version = "0.4", features = ["serde"] }
pcap = "1.1"
libc = "0.2"

# Windows-specific dependencies for Npcap/WinPcap support
[target.'cfg(windows)'.dependencies]
# Additional Windows-specific dependencies can be added here if needed

# Platform-specific build configuration
[package.metadata.cross.target.x86_64-pc-windows-msvc]
pre-build = []

[package.metadata.cross.target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture arm64",
    "apt-get update && apt-get install -y libpcap-dev:arm64 pkg-config",
]

[package.metadata.cross.target.armv7-unknown-linux-gnueabihf]
pre-build = [
    "dpkg --add-architecture armhf",
    "apt-get update && apt-get install -y libpcap-dev:armhf pkg-config",
]


[build-dependencies]
chrono = { version = "0.4", features = ["serde"] }

[[bin]]
name = "ptp-trace"
path = "src/main.rs"
