# Cross.toml - Configuration for cross-rs cross-compilation

[build.env]
passthrough = [
    "LIBPCAP_LIBDIR",
    "LIBPCAP_VER",
    "PKG_CONFIG_PATH",
    "PKG_CONFIG_LIBDIR",
    "PKG_CONFIG_SYSROOT_DIR",
]

# ARM64 / aarch64 target configuration
[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/cross:aarch64-unknown-linux-gnu"
pre-build = [
    "dpkg --add-architecture arm64",
    "apt-get update && apt-get install -y libpcap0.8-dev:arm64 pkg-config:arm64",
    "ln -sf /usr/lib/aarch64-linux-gnu/pkgconfig/libpcap.pc /usr/lib/pkgconfig/",
]

[target.aarch64-unknown-linux-gnu.env]
PKG_CONFIG_PATH = "/usr/lib/aarch64-linux-gnu/pkgconfig"
PKG_CONFIG_LIBDIR = "/usr/lib/aarch64-linux-gnu/pkgconfig"
PKG_CONFIG_SYSROOT_DIR = "/"
LIBPCAP_LIBDIR = "/usr/lib/aarch64-linux-gnu"

# ARM32 / armv7 target configuration
[target.armv7-unknown-linux-gnueabihf]
image = "ghcr.io/cross-rs/cross:armv7-unknown-linux-gnueabihf"
pre-build = [
    "dpkg --add-architecture armhf",
    "apt-get update && apt-get install -y libpcap0.8-dev:armhf pkg-config",
    "ln -sf /usr/lib/arm-linux-gnueabihf/pkgconfig/libpcap.pc /usr/lib/pkgconfig/",
]

[target.armv7-unknown-linux-gnueabihf.env]
PKG_CONFIG_PATH = "/usr/lib/arm-linux-gnueabihf/pkgconfig"
PKG_CONFIG_LIBDIR = "/usr/lib/arm-linux-gnueabihf/pkgconfig"
PKG_CONFIG_SYSROOT_DIR = "/"
LIBPCAP_LIBDIR = "/usr/lib/arm-linux-gnueabihf"

# x86_64 Linux (native, but included for completeness)
[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/cross:x86_64-unknown-linux-gnu"
pre-build = ["apt-get update && apt-get install -y libpcap-dev pkg-config"]

[target.x86_64-unknown-linux-gnu.env]
PKG_CONFIG_PATH = "/usr/lib/x86_64-linux-gnu/pkgconfig"
LIBPCAP_LIBDIR = "/usr/lib/x86_64-linux-gnu"
