# Cross.toml - Configuration for cross-rs cross-compilation

[build.env]
passthrough = [
    "LIBPCAP_LIBDIR",
    "LIBPCAP_VER",
    "PKG_CONFIG_PATH",
    "PKG_CONFIG_LIBDIR",
    "PKG_CONFIG_SYSROOT_DIR",
]

# ARM64 / aarch64 target configuration
[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture arm64",
    "apt-get update && apt-get install -y libpcap0.8-dev:arm64 pkg-config",
]

# ARM32 / armv7 target configuration
[target.armv7-unknown-linux-gnueabihf]
pre-build = [
    "dpkg --add-architecture armhf",
    "apt-get update && apt-get install -y libpcap0.8-dev:armhf pkg-config",
]

# x86_64 Linux (for consistency)
[target.x86_64-unknown-linux-gnu]
pre-build = ["apt-get update && apt-get install -y libpcap-dev pkg-config"]
